n = 123
f = 456.789
s1 = '\'Hello, world\''
s2 = r"'Hello,\'Adam\''"
s3 = r"r'Hello," + "\t\"Bart\"'"
s4 = r"r'''Hello,"+"\nLisa!\'\'\'"
print('n = ',n,
'\nf = ',f,
'\ns1 = ',s1,
'\ns2 = ',s2,
'\ns3 = ',s3,
'\ns4 = ',s4)
